const parse = h => new DOMParser().parseFromString(h, 'text/html');
const base = () => updateRoot(createState(T), {customerName:'山田商事', contactName:'山田'});

test('preview: 未選択のみ→空ページ＋確認ページ', () => { const d = parse(renderPreview(base(), 'L')); assertEqual(d.querySelectorAll('.page').length, 2); assertTrue(d.querySelector('.page-empty') !== null); });
test('preview: 仕様2件＋確認＝3ページ・ページ番号', () => { let s = addSpec(base()); s = updateSpec(s, 0, {model:OPTIONS.model[0]}); s = updateSpec(s, 1, {model:OPTIONS.model[3]}); const d = parse(renderPreview(s, 'L')); const pages = d.querySelectorAll('.page'); assertEqual(pages.length, 3); assertTrue(pages[0].textContent.includes(specName(s, 0))); assertTrue(pages[1].textContent.includes(specName(s, 1))); assertEqual(pages[2].querySelector('.page-no').textContent.trim(), '3 / 3'); });
test('preview: ヘッダーに日付・宛名', () => { let s = updateSpec(base(), 0, {model:OPTIONS.model[0]}); const t = parse(renderPreview(s, 'L')).querySelector('.page').textContent; assertTrue(t.includes('2026年10月9日')); assertTrue(t.includes('山田商事')); assertTrue(t.includes('山田')); });
test('preview: 未選択は—、複数選択は改行', () => { let s = updateSpec(base(), 0, {model:OPTIONS.model[0], windows:[OPTIONS.windows[0], OPTIONS.windows[1]]}); const d = parse(renderPreview(s, 'L')); const rows = [...d.querySelectorAll('.spec-table tr')]; const row = l => rows.find(r => r.textContent.includes(l)); assertTrue(row('屋根材').textContent.includes('—')); assertEqual(row('オプション窓ガラス').querySelectorAll('br').length, 1); });
test('preview: 特記事項はエスケープ＋改行保持', () => { let s = updateSpec(base(), 0, {model:OPTIONS.model[0], specNote:'<b>1行目</b>&\n2行目'}); const html = renderPreview(s, 'L'); assertTrue(html.includes('&lt;b&gt;1行目&lt;/b&gt;&amp;<br>2行目')); });
test('preview: 宛名もエスケープ', () => { const s = updateRoot(base(), {customerName:'<script>x</script>'}); assertTrue(!renderPreview(s, 'L').includes('<script>x')); });
test('preview: 熱源その他の内容は条件付き', () => { let s = updateSpec(base(), 0, {model:OPTIONS.model[0], heater:OPTIONS.heater[0]}); assertTrue(!renderPreview(s, 'L').includes('熱源（その他の内容）')); s = updateSpec(s, 0, {heater:HEATER_OTHER, heaterOther:'持込'}); assertTrue(renderPreview(s, 'L').includes('持込')); });
test('preview: 事前確認の回答', () => { let s = setCheck(base(), 'electrical', 'はい'); const last = [...parse(renderPreview(s, 'L')).querySelectorAll('.page')].pop(); assertTrue(last.textContent.includes('事前確認事項')); assertTrue(last.textContent.includes('はい')); assertTrue(last.textContent.includes('—')); });
test('preview: 仕様表のtheadに共通ヘッダーと仕様名（2枚目にも繰り返す）', () => { let s = updateSpec(base(), 0, {model:OPTIONS.model[0], destination:'千葉県'}); const d = parse(renderPreview(s, 'L')); const head = d.querySelector('.spec-table thead'); assertTrue(head !== null, 'thead'); assertTrue(head.textContent.includes('バレルサウナ仕様確認書')); assertTrue(head.textContent.includes('山田商事')); assertEqual(head.querySelector('.spec-title').textContent, '20261009_山田商事様_千葉県_i – barrel Tiny R12_仕様①'); });
test('preview: 離島の行は配送先の直後', () => { let s = updateSpec(base(), 0, {model:OPTIONS.model[0], destination:'沖縄県', remoteIsland:'あり'}); const rows = [...parse(renderPreview(s, 'L')).querySelectorAll('.spec-table tbody tr')].map(r => r.textContent); const i = rows.findIndex(t => t.startsWith('配送先')); assertTrue(rows[i + 1].includes('離島') && rows[i + 1].includes('あり')); });
test('preview: 表題は「バレルサウナ仕様確認書」', () => { const h = renderPreview(base(), 'L'); assertTrue(h.includes('バレルサウナ仕様確認書')); assertTrue(!h.includes('構成確認書')); });
