const T = new Date(2026, 9, 9);

test('createState: 当日・仕様1つ', () => { const s = createState(T); assertEqual(s.date, '2026-10-09'); assertEqual(s.specs.length, 1); assertEqual(s.activeIndex, 0); });
test('addSpec: 5で頭打ち・新タブがactive', () => { let s = createState(T); for (let k = 0; k < 6; k++) s = addSpec(s); assertEqual(s.specs.length, 5); assertEqual(s.activeIndex, 4); });
test('duplicateSpec: 深いコピー', () => { let s = updateSpec(createState(T), 0, {roof:'あり', windows:['x']}); s = duplicateSpec(s, 0); assertEqual(s.specs[1].roof, 'あり'); s.specs[1].windows.push('y'); assertEqual(s.specs[0].windows, ['x']); assertEqual(s.activeIndex, 1); });
test('duplicateSpec: 5つ時は無変化', () => { let s = createState(T); for (let k = 0; k < 4; k++) s = addSpec(s); assertEqual(duplicateSpec(s, 0).specs.length, 5); });
test('removeSpec: 最後の1つは消せない', () => { assertEqual(removeSpec(createState(T), 0).specs.length, 1); });
test('removeSpec: active より前を消すと active が詰まる', () => { let s = addSpec(addSpec(createState(T))); s = setActive(s, 2); s = removeSpec(s, 0); assertEqual(s.activeIndex, 1); assertEqual(s.specs.length, 2); });
test('removeSpec: 末尾の active を消すと範囲内', () => { let s = addSpec(addSpec(createState(T))); s = removeSpec(s, 2); assertEqual(s.activeIndex, 1); });
test('updateSpec: 配送なしで配送方法クリア', () => { let s = updateSpec(createState(T), 0, {destination:'千葉県', deliveryMethod:OPTIONS.deliveryMethod[0]}); s = updateSpec(s, 0, {destination:NO_DELIVERY}); assertEqual(s.specs[0].deliveryMethod, ''); s = updateSpec(s, 0, {destination:'千葉県'}); assertEqual(s.specs[0].deliveryMethod, ''); });
test('updateSpec: 配送なし中は配送方法を設定できない', () => { let s = updateSpec(createState(T), 0, {destination:NO_DELIVERY}); s = updateSpec(s, 0, {deliveryMethod:OPTIONS.deliveryMethod[0]}); assertEqual(s.specs[0].deliveryMethod, ''); });
test('updateSpec: 熱源をその他以外にすると内容クリア', () => { let s = updateSpec(createState(T), 0, {heater:HEATER_OTHER, heaterOther:'自社手配'}); s = updateSpec(s, 0, {heater:OPTIONS.heater[0]}); assertEqual(s.specs[0].heaterOther, ''); });
test('updateSpec: 入力を変更しない', () => { const s = createState(T); updateSpec(s, 0, {roof:'あり'}); assertEqual(s.specs[0].roof, ''); });
test('printableSpecs: 規格未選択は除外・番号はタブ番号', () => { let s = addSpec(addSpec(createState(T))); s = updateSpec(s, 1, {model:OPTIONS.model[0]}); assertEqual(printableSpecs(s).map(p => p.number), [2]); });
test('sanitizeState: 不正入力は初期状態', () => { assertEqual(sanitizeState('壊れた', T), createState(T)); assertEqual(sanitizeState(null, T), createState(T)); });
test('sanitizeState: 消えた選択肢は未選択・欠落補完', () => { const s = sanitizeState({date:'2026-01-02', specs:[{model:'旧モデル', windows:['旧窓', OPTIONS.windows[0]], destination:'火星'}], checks:{electrical:'はい', foundation:'たぶん'}, activeIndex:9}, T); assertEqual(s.specs[0].model, ''); assertEqual(s.specs[0].windows, [OPTIONS.windows[0]]); assertEqual(s.specs[0].destination, ''); assertEqual(s.specs[0].roof, ''); assertEqual(s.checks.electrical, 'はい'); assertEqual(s.checks.foundation, ''); assertEqual(s.activeIndex, 0); assertEqual(s.date, '2026-01-02'); });
test('sanitizeState: 6つ以上は5に切り詰め', () => { const s = sanitizeState({specs:[{},{},{},{},{},{}]}, T); assertEqual(s.specs.length, 5); });
test('formatDateJa', () => { assertEqual(formatDateJa('2026-10-09'), '2026年10月9日'); assertEqual(formatDateJa(''), '—'); });
test('specNumberLabel', () => { assertEqual([1,2,3,4,5].map(specNumberLabel).join(''), '①②③④⑤'); });
test('OPTIONS: spec表記', () => { assertEqual(OPTIONS.model.length, 8); assertTrue(OPTIONS.model.includes('i – barrel Medium-Long R275（軒あり）')); assertEqual(PREFECTURES.length, 47); assertEqual(PRECHECKS.length, 5); assertEqual(OPTIONS.heater.length, 10); });
test('OPTIONS: 窓ガラスの順序と【OP】なし', () => { assertEqual(OPTIONS.windows, ['大窓：背面 強化ガラス窓（1枚）', '縦長窓：強化ガラス窓（2枚） 前面', '縦長窓：強化ガラス窓（2枚） 背面', '横長窓：腰位置・側面 強化ガラス窓（2枚）', '半円パノラマ 強化ガラス窓（1枚）']); });
test('離島: 初期値・選択肢・配送先の直後', () => { assertEqual(createSpec().remoteIsland, ''); assertEqual(OPTIONS.remoteIsland, ['あり', 'なし']); const keys = SPEC_FIELDS.map(f => f.key); assertEqual(keys[keys.indexOf('destination') + 1], 'remoteIsland'); });
test('離島: 配送なしでクリア', () => { let s = updateSpec(createState(T), 0, {destination:'沖縄県', remoteIsland:'あり'}); s = updateSpec(s, 0, {destination:NO_DELIVERY}); assertEqual(s.specs[0].remoteIsland, ''); });
test('createState: 担当者名の初期値は深山', () => { assertEqual(createState(T).contactName, '深山'); });
test('specName: 日付_お客様名_都道府県_規格_仕様番号', () => { let s = updateRoot(addSpec(createState(T)), {customerName:'山田商事'}); s = updateSpec(s, 1, {destination:'千葉県', model:OPTIONS.model[1]}); assertEqual(specName(s, 1), '20261009_山田商事_千葉県_i – barrel Small R15_仕様②_初版'); });
test('specName: 未入力の部分は省く', () => { const s = updateRoot(createState(T), {date:''}); assertEqual(specName(s, 0), '仕様①_初版'); assertEqual(specName(updateSpec(s, 0, {destination:NO_DELIVERY}), 0), '配送なし_仕様①_初版'); });
test('specName: 入力欄としての仕様名はない', () => { assertTrue(!SPEC_FIELDS.some(f => f.key === 'name')); assertTrue(!('name' in createSpec())); });
test('pdfTitle: 1仕様なら仕様名と同じ', () => { let s = updateRoot(addSpec(createState(T)), {customerName:'山田商事'}); s = updateSpec(s, 1, {destination:'千葉県', model:OPTIONS.model[1]}); assertEqual(pdfTitle(s), specName(s, 1)); });
test('pdfTitle: 複数仕様は先頭の仕様の内容＋仕様番号を並べる', () => { let s = updateRoot(addSpec(addSpec(createState(T))), {customerName:'山田商事'}); s = updateSpec(s, 0, {destination:'千葉県', model:OPTIONS.model[5]}); s = updateSpec(s, 2, {destination:'東京都', model:OPTIONS.model[1]}); assertEqual(pdfTitle(s), '20261009_山田商事_千葉県_i – barrel Large R35（軒あり・前室あり）_仕様①③_初版'); });
test('pdfTitle: ファイル名に使えない文字は置き換える', () => { let s = updateRoot(createState(T), {customerName:'A/B:C*?"<>|\\D'}); s = updateSpec(s, 0, {model:OPTIONS.model[0]}); assertEqual(pdfTitle(s), '20261009_A-B-C-------D_i – barrel Tiny R12_仕様①_初版'); });
test('版: 初期値は初版(0)・表記', () => { assertEqual(createSpec().revision, 0); assertEqual(revisionLabel(0), '初版'); assertEqual(revisionLabel(1), '更新版1'); assertEqual(revisionLabel(12), '更新版12'); });
test('版: 仕様名の末尾に付く', () => { const s = updateSpec(createState(T), 0, {revision:2}); assertEqual(specName(s, 0), '20261009_仕様①_更新版2'); });
test('版: 複数仕様のPDF名は先頭の仕様の版', () => { let s = addSpec(createState(T)); s = updateSpec(s, 0, {model:OPTIONS.model[0], revision:1}); s = updateSpec(s, 1, {model:OPTIONS.model[1], revision:3}); assertTrue(pdfTitle(s).endsWith('_仕様①②_更新版1')); });
test('版: 不正な保存値は初版、範囲外は丸める', () => { const s = sanitizeState({specs:[{revision:'x'}, {revision:-3}, {revision:2.5}, {revision:5}, {revision:1000}]}, T); assertEqual(s.specs.map(p => p.revision), [0, 0, 0, 5, MAX_REVISION]); });
